version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/core
    ports:
      - "3000:3000"
      - "1025:1025"
    depends_on:
      - db
    links:
      - redis
    stdin_open: true
    tty: true
    environment:
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis
